### ISSUE TITLE
Ubuntu 24.04 deb install issues

### ISSUE THREAD

**Issue by gravitybacklight** [aptakube/aptakube#230] opened 2024-05-15 13:08 UTC
### Current and expected behavior

trying to install 1.6.6 results in a dependency issue with Ubuntu 24.04:

` sudo dpkg -i aptakube_1.6.6_amd64.deb 
...
dpkg: dependency problems prevent configuration of aptakube:
 aptakube depends on libwebkit2gtk-4.0-37; however:
  Package libwebkit2gtk-4.0-37 is not installed.
`

ubuntu 24 only offers libwebkit2gtk-4.1-0

Using the appimage for now.

### Environment & Operating System

PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"

**Comment by goenning** [comment] 2024-05-16 10:26
Related: https://github.com/tauri-apps/tauri/issues/9662

We use Tauri 1.x and they have a hard dependency on libwebkit2gtk-4.0-37, which seems like was recently removed from Ubuntu 24.04?

If you downgrade to 1.6.5, does it still work?

This seems to be the best work around for now: https://github.com/gitbutlerapp/gitbutler/issues/3675#issuecomment-2103688048

The definitive solution is for Aptakube to move to Tauri 2.x, which is still in beta, so that'll take some time

**Comment by gravitybacklight** [comment] 2024-05-16 11:40
1.6.5 has the same problem.

I'm also getting lots of "unexpected error" messages when trying to use the appimage on ubuntu 24.

![image](https://github.com/aptakube/aptakube/assets/2327204/38e816e6-f3cd-40ba-8f60-e90241648a58)

That was with an attempt to edit a yaml file. but also get it if i switch to a different cluster.

**Comment by jibon0070** [comment] 2024-05-16 12:37
https://github.com/gitbutlerapp/gitbutler/issues/3675#issuecomment-2103688048

**Comment by segler-alex** [comment] 2024-05-23 08:21
+1

**Comment by SoGooDFR** [comment] 2024-06-06 13:49
> 1.6.5 has the same problem.
> 
> I'm also getting lots of "unexpected error" messages when trying to use the appimage on ubuntu 24.
> 
> ![image](https://private-user-images.githubusercontent.com/2327204/331187904-38e816e6-f3cd-40ba-8f60-e90241648a58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2ODIwNjcsIm5iZiI6MTcxNzY4MTc2NywicGF0aCI6Ii8yMzI3MjA0LzMzMTE4NzkwNC0zOGU4MTZlNi1mM2NkLTQwYmEtOGY2MC1lOTAyNDE2NDhhNTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDZUMTM0OTI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDkzNDdiOThhZTk1Mjc3ZmQ4OGQ4N2MzNzczMDVmZDc0OTAwYzE1ODQyYWEwMWRlOTBiZjZlNTFkMzRmNDAyMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-28OwEhM9Xbf0SvDbG26PjVm6bQf-QL4_mdAW8mk1Ws)
> 
> That was with an attempt to edit a yaml file. but also get it if i switch to a different cluster.

+1

**Comment by goenning** [comment] 2024-06-06 14:56
@SoGooDFR is that something you’re reproducing consistently? Is that also when editing YAML?

**Comment by mschneider82** [comment] 2024-06-18 06:17
I have updated from ubuntu 22.04 to 23.10 then 24.04 and aptakube, and also the updates work fine:

that packages are installed:
ii  libwebkit2gtk-4.0-37:amd64  2.44.0-0ubuntu0.23.10.1 amd64        Web content engine library for GTK
ii  libwebkit2gtk-4.0-dev:amd64 2.44.0-0ubuntu0.23.10.1 amd64        Web content engine library for GTK - development files
ii  libwebkit2gtk-4.1-0:amd64   2.44.2-0ubuntu0.24.04.1 amd64        Web content engine library for GTK

You can see that it uses the libwebkit2gtk-4.0-37 package from 23.10, i think you can download the deb files and install it manually. https://packages.ubuntu.com/mantic/libwebkit2gtk-4.0-37

**Comment by SoGooDFR** [comment] 2024-06-21 13:42
Release 1.6.10 fix the yaml editing issue and graphical issue on Ubuntu 24.04LTS

**Comment by goenning** [comment] 2024-09-11 08:12
For anyone having this issue, I'm working on a new version that solves this dependency issue.

You can try the beta here: https://releases.aptakube.com/aptakube_1.8.0-beta1_amd64.deb

**Comment by goenning** [comment] 2024-09-29 18:33
Closing this now as it’s fixed on the latest version. But as usual, please let me know if you’re still having issues

**Closed by goenning** 2024-09-29 18:33 UTC
Labels: bug, upstream-dependency
