### ISSUE TITLE
Open shell doesn't work

### ISSUE THREAD

**Issue by dmeijboom** [aptakube/aptakube#158] opened 2023-09-14 19:07 UTC
### Current and expected behavior

When I click "Pod Shell" for a pod a new terminal session is started in the terminal but all I see on the screen is:

```bash
export KUBECONFIG=[redacted].yml:[redacted].yml
```

Nothing else happens.

### Environment & Operating System

mac OS: 13.4.1
Terminal: iTerm2
Aptakube version: 1.5.9

**Comment by dmeijboom** [comment] 2023-09-14 19:07
Note that `kubectl exec -it (..)` works just fine

**Comment by goenning** [comment] 2023-09-19 19:17
@dmeijboom Did that issue start recently? 

It's weird how that's being printed, because the command the app should look like this:

```
KUBECONFIG=/Users/goenning/.kube/config kubectl exec metrics-server-6588d95
b98-slbjk --context minikube -n kube-system ...
```

**Comment by dmeijboom** [comment] 2023-09-20 11:58
> @dmeijboom Did that issue start recently? 
> 
> 
> 
> It's weird how that's being printed, because the command the app should look like this:
> 
> 
> 
> ```
> 
> KUBECONFIG=/Users/goenning/.kube/config kubectl exec metrics-server-6588d95
> 
> b98-slbjk --context minikube -n kube-system ...
> 
> ```

Yes, I updated the app (haven't updated in a while) and noticed it didn't work anymore.

Note that I have several kubeconfig YAML files. The config for each cluster is stored in its own config file.

**Comment by goenning** [comment] 2023-09-21 09:16
Can you try using Apple Terminal instead to see if this is specific to Apta+iTerm? 
Temporarily renaming iTerm.app to something on /Applications should be enough for Apta to switch to Terminal.

**Comment by dmeijboom** [comment] 2023-09-21 11:35
> Can you try using Apple Terminal instead to see if this is specific to Apta+iTerm? Temporarily renaming iTerm.app to something on /Applications should be enough for Apta to switch to Terminal.

It also happens with Apple Terminal. I hear a sound, which repeats a couple of times, indicating that its trying to type or send text to the terminal but it doesn't show anything beyond `KUBECONFIG=...`

**Comment by goenning** [comment] 2023-10-02 18:35
Sorry for the delay!

That actually helps a bit. We use AppleScript to do that automation and the actual script is stored at `$TMPDIR/aptakube-shell.osascript` and updated before each shell session starts.

What happens when you execute it like this:

```
osascript $TMPDIR/aptakube-shell.osascript
```

I suspect you'll hear the same sound. can you try simplify the command, maybe removing the `KUBECONFIG=` or other bits just to see if we can find what's causing this? Thanks!

**Comment by dmeijboom** [comment] 2023-10-02 19:43
> Sorry for the delay!
> 
> That actually helps a bit. We use AppleScript to do that automation and the actual script is stored at `$TMPDIR/aptakube-shell.osascript` and updated before each shell session starts.
> 
> What happens when you execute it like this:
> 
> ```
> osascript $TMPDIR/aptakube-shell.osascript
> ```
> 
> I suspect you'll hear the same sound. can you try simplify the command, maybe removing the `KUBECONFIG=` or other bits just to see if we can find what's causing this? Thanks!

It looks like the `write text` instruction stops at around `1024` characters. If I remove just enough characters from the `KUBECONFIG` environment variable it works.

**Comment by goenning** [comment] 2023-10-02 20:08
How many kubeconfigs are being concatenated on the script?

I suspect there is a bug that is selecting multiple kubeconfigs unnecessarily. 

the script should only contain the config files related to the context used on the kubectl command. If you have dozens of configs, and each config has 1 context (+user +cluster), then it should only have that kubeconfig on the apple script.

**Comment by dmeijboom** [comment] 2023-10-03 07:46
> How many kubeconfigs are being concatenated on the script?

All of them. The `KUBECONFIG` environment variable in the osascript file looks like this: `KUBECONFIG=/path/configfile1.yml:/path/configfile2.yml:/path/configfile3.yml` etc.

> I suspect there is a bug that is selecting multiple kubeconfigs unnecessarily.

That seems to be the issue. If only the configfile for the selected cluster would be included in the `KUBECONFIG` environment variable it will work.

**Comment by goenning** [comment] 2023-10-04 15:38
@dmeijboom thank you, I was able to reproduce it. Please give it a try with the latest version 1.5.11, it should be fixed now!

**Comment by dmeijboom** [comment] 2023-10-04 15:59
Works like a charm!! Thanks :)

**Closed** 2023-10-04 15:59 UTC
Labels: bug
