### ISSUE TITLE
Too many new windows when open a new window

### ISSUE THREAD

**Issue by RonStein2000** [aptakube/aptakube#325] opened 2024-10-31 12:00 UTC
### Current and expected behavior

when I have two or more windows open and want to open another new window, the app opens 3 or even more windows with the list of avaiulable clusters., I would expect only one new window.
Its also a bit annoying, that I cannot see a list of open windows in some place to select the window.
I am on Mac OS 15.1

### Environment & Operating System

macOS 15.1

**Comment by goenning** [comment] 2024-10-31 15:31
Closing this as duplicate of https://github.com/aptakube/aptakube/issues/322

As for the list of open windows, if you right click on the app at the Dock there's a "Show All Windows"

**Closed by goenning** 2024-10-31 15:31 UTC
Labels: bug
