### ISSUE TITLE
logs of init containers

### ISSUE THREAD

**Issue by mschneider82** [aptakube/aptakube#107] opened 2023-05-11 11:47 UTC
### Current and expected behavior

I have a Cronjob which starts an Job that has 8 initContainers and one (final) Container, initContainers runs sequential not parallel like the final Container.

The job is completed after some time. Currently i can only see the logs of the FinalContainer and cannot select the logs of the init containers. Pods&Containers button shows just 1. I can see all logs in Lens of each init and final container

### Environment & Operating System

ubuntu appimage latest

**Comment by goenning** [comment] 2023-05-11 14:17
Going to close this as a duplicate of https://github.com/aptakube/aptakube/issues/91 as InitContainers are not yet supported, but it'll be very shortly!

**Closed by goenning** 2023-05-11 14:17 UTC
Labels: bug
