### ISSUE TITLE
Can not connect to VMWare Cluster using OIDC

### ISSUE THREAD

**Issue by tharwan** [aptakube/aptakube#221] opened 2024-04-15 12:03 UTC
### Current and expected behavior

with a valid kubeconfig I can not connect to our VMWare Cluster.
<img width="479" alt="Screenshot 2024-04-15 at 13 36 31" src="https://github.com/aptakube/aptakube/assets/964241/95e2d3a9-a5d3-4060-8eb0-bcdda8eb2939">

### Environment & Operating System

macOS 14.3.1 (23D60)
Aptakube Version 1.6.3 
Kubelet v1.26.10

**Comment by goenning** [comment] 2024-04-15 17:02
I suppose it works on kubectl right? It'd help me a lot if you could share a redacted version of your kubeconfig privately on Discord or email, is that doable? At least the `user` section.

The last time I saw something like this was when there were multiple kubeconfig files with duplicate names being used, so there was some confusion where it was using the name/url of the cluster from one kubeconfig, but the auth from another file. So just confirm if that you're using a single kubeconfig, or if there's multiple, that none of them have duplicate context/cluster/user names

**Comment by tharwan** [comment] 2024-04-16 07:47
I can confirm that I have only one config file. There are two clusters and contexts that have a similar name if that plays a role.

**Comment by goenning** [comment] 2024-04-18 09:06
note to self: this is caused by missing OIDC feature on Aptakube

**Comment by goenning** [comment] 2024-04-25 08:44
This should be fixed on 1.6.5! Thanks for reporting it

**Closed by goenning** 2024-04-25 08:44 UTC
Labels: bug
