### ISSUE TITLE
Lots of "Unexpected Error" pop-ups after upgrading to 1.7.10

### ISSUE THREAD

**Issue by mboutet** [aptakube/aptakube#304] opened 2024-10-03 13:05 UTC
### Current and expected behavior

<img width="244" alt="Screenshot 2024-10-03 at 8 57 29 AM" src="https://github.com/user-attachments/assets/a9c47b55-518e-4996-84e8-05ee3c3f1602">

I will get those whenever I am switching resources. Sometimes, there are more than 10 popping up and vertically filling the right hand side of the interface. I usually have about 10 contexts enabled and I have cluster-admin privileges on all the clusters.

Those pop-ups were not there prior to 1.7.10 (I usually keep up to date with every releases of Aptakube).

### Environment & Operating System

```
Version 1.7.10 (20240930.101152)
K8s 1.28.x (mix of EKS + CAPI on-prem)
macOS 13.6.2 (22G320)
Apple M2 Max
```

**Comment by goenning** [comment] 2024-10-03 13:41
Did you notice anything that does not work when that happens? Or just the annoying popup?

**Comment by mboutet** [comment] 2024-10-03 13:50
I'm not noticing anything that is not working, so I would say just the annoying popup 😛

However, it might be useful to be able to get more details on what's wrong to make sure it's not an actual issue.

**Comment by goenning** [comment] 2024-10-03 14:58
100% Agree, the issue is that `Load failed` is a generic error from WebKit that doesn't give us any extra info :(

> I will get those whenever I am switching resources

Does this happen all the time? I'm trying to reproduce but I can't. And by `switching resources` you mean something like clicking on a Pod? Or is it the `Cmd+K` shortcut?

**Comment by mboutet** [comment] 2024-10-03 15:08
> And by switching resources

When clicking on any resource (even custom ones) on the left sidebar or by using `Cmd+K`.

> Does this happen all the time?

It appears to be happening when Aptakube needs to refresh the objects of a given type after not visiting that type for some time. For example, if I click on Pod, then switch to something else, then go back to Pod after a few minutes, it's usually fine. It also happens on new Aptakube windows instance (opened through `Cmd+click`).

**Comment by goenning** [comment] 2024-10-04 17:57
I still can’t reproduce, but I think I know what it is and have a potential fix for it coming 🤞

**Comment by goenning** [comment] 2024-10-08 14:17
Version 1.7.11 might have a fix for this, can you give it a try?

**Comment by mboutet** [comment] 2024-10-08 14:17
Yes, it does fix the issue! Thank you!

**Comment by goenning** [comment] 2024-10-08 14:18
Damm, that was quick!

**Comment by goenning** [comment] 2024-10-08 14:18
And GitHub auto updating the comments section made me feel like I was on Discord 😂

**Closed by goenning** 2024-10-08 14:18 UTC
Labels: bug
