### ISSUE TITLE
Integrated terminal in the application

### ISSUE THREAD

**Issue by PlugaruT** [aptakube/aptakube#198] opened 2023-12-28 10:56 UTC
### What problem are you trying to solve? Do you a suggestion on how to solve it?

Right now, a separate terminal window opens and it works nice, but it's distracting. 
It would be nice to have it integrated in the application as a tab or something else.

**Comment by beeblebrox3** [comment] 2024-01-19 20:38
I'm using on a Mac and when I open the console it opens two windows of iTerm. Both windows stay on background until I manually change the focus. I'm new into the macOS world and don't know if this is common, but is the only app that has this behavior with me.

And I'm a warp user, so I have to use another terminal app, not my default one (but this is a macOS problem I think).
An integrated terminal would be great for the app, like most IDEs and lens.

**Comment by goenning** [comment] 2024-01-31 15:20
I just noticed this is a duplicate of #86 which has more upvotes, I'll close this one in favour of the other one

@DanTulovsky when this is implemented, it'll definitely be configurable, there's a lot of people who prefer external ones

**Closed by goenning** 2024-01-31 15:20 UTC
Labels: feature request
