### ISSUE TITLE
Helm charts without resources show up without name

### ISSUE THREAD

**Issue by mhulscher** [aptakube/aptakube#165] opened 2023-09-22 12:22 UTC
### Current and expected behavior

On 1.5.10.

I install multiple helm-charts that only apply manifests that are part of a [chart hook.](https://helm.sh/docs/topics/charts_hooks/) These don't show up in the UI.

![image](https://github.com/aptakube/aptakube/assets/18721288/1deb6034-52c2-4cb8-9bb4-fba4919b1aee)

![image](https://github.com/aptakube/aptakube/assets/18721288/b91c4449-7548-4c19-989e-99c2ca33b98d)

### Environment & Operating System

Kubuntu 23.10 pre-release

AKS

```
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
```

**Comment by goenning** [comment] 2023-09-22 13:06
Thanks for the bug report @mhulscher 

That happens when the apps fails to deserialize the object. Could you have a look at the logs as there should be something there that would help me find the root cause.


```
~/.config/com.aptakube.Aptakube/logs/Aptakube.log
```

**Comment by mhulscher** [comment] 2023-09-25 08:27
This could be a candidate:

```
[2023-09-22][12:16:47][ERROR][aptakube::k8s::helm] Failed to convert secret to helm release: failed to deserialize HelmRelease: missing field `manifest` at line 1 column 13846
```

**Comment by goenning** [comment] 2023-10-04 15:36
@mhulscher this should be fixed on the new version, but please reopen if it's not!

**Closed by goenning** 2023-10-04 15:36 UTC
Labels: bug
